# config.yaml - Configuration for MORE Qualitative Analysis Pipeline

# Model Configuration
models:
  llama:
    model_path: "meta-llama/Llama-3-70b-chat-hf"
    quantization: true
    max_new_tokens: 500
    temperature: 0.7
    top_p: 0.9
  
  bert:
    use_clinical: true
    model_name: "emilyalsentzer/Bio_ClinicalBERT"
    max_length: 512
    
# Analysis Parameters
analysis:
  n_codes: 20
  n_clusters: 15
  min_code_coverage: 0.1
  similarity_threshold: 0.7
  
  # Iterative refinement
  n_iterations: 3
  interactive_refinement: true
  
# MORE-specific Theoretical Domains
theoretical_domains:
  attention_regulation:
    - focus
    - concentration
    - awareness
    - distraction
    - mindfulness
    
  pain_experience:
    - pain
    - discomfort
    - sensation
    - relief
    - intensity
    
  avoidance_patterns:
    - escape
    - avoid
    - fear
    - resistance
    - denial
    
  metacognitive_awareness:
    - noticing
    - observing
    - awareness of awareness
    - monitoring
    - reflection
    
  reappraisal:
    - reframe
    - perspective
    - acceptance
    - non-judgment
    - reinterpretation
    
  savoring:
    - pleasure
    - enjoyment
    - appreciation
    - positive
    - gratitude
    
  somatic_awareness:
    - body
    - physical
    - sensation
    - breath
    - embodiment
    
  therapeutic_engagement:
    - motivation
    - practice
    - commitment
    - goals
    - adherence

# PURER Framework Components
purer_framework:
  phenomenology:
    - "What did you notice?"
    - "Can you describe your experience?"
    - "What sensations arose?"
    
  utilization:
    - "How might you use this?"
    - "When could you apply this technique?"
    
  reframing:
    - "What's another way to look at this?"
    - "How else might you interpret this?"
    
  education:
    - "This is a common experience"
    - "The technique works by"
    
  reinforcement:
    - "That's excellent progress"
    - "You're developing this skill"

# File Paths
paths:
  transcript_dir: "more_transcripts"
  output_dir: "analysis_output"
  codebook_dir: "codebooks"
  reports_dir: "clinical_reports"
  
# Output Formats
output:
  formats:
    - excel
    - csv
    - json
    - redcap
  
  report_sections:
    - code_frequencies
    - therapeutic_progression
    - network_analysis
    - clinical_insights
    
# Validation Settings
validation:
  min_kappa: 0.7
  min_agreement: 0.8
  
# Privacy and Compliance
privacy:
  deidentify: true
  local_processing: true
  encryption: true
